name: 'Configure AWS Credentials'
description: 'Configura as credenciais da AWS usando OIDC'
inputs:
  role-to-assume:
    description: 'ARN da role da AWS a ser assumida'
    required: true
  aws-region:
    description: 'Região da AWS'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ inputs.aws-region }}